### ISSUE TITLE
baseline_reproduce

### ISSUE THREAD

**Issue by lxuniverse** [superrrpotato/Defending-Neural-Backdoors-via-Generative-Distribution-Modeling#1]
Hi,

Thanks for sharing your code.

It seems the baseline experiments(point_defend_cifar_10) code are not complete. Could you check and provide some help for searching in point mode?

Thanks,
Xiang

**Comment by superrrpotato** [comment]
Hey,
Thanks for your interest on my project!  I am quite sure that I did my experiment using the current code. Could you provide more information about why you think the baseline experiment code is not complete?

**Comment by superrrpotato** [comment]
Oh. I see, to run the baseline experiment, I need to generate some searching result patterns using the baseline methods before running this baseline experiments, and I did not include that part in this code. Sorry about that, I will upload that part later. Thanks for pointing it out.

**Comment by superrrpotato** [comment]
Hi Xiang,
I just uploaded something I found helpful. I wish this could help you with your problem.
Best wishes,
Yukun

**Comment by lxuniverse** [comment]
> Hi Xiang,
> I just uploaded something I found helpful. I wish this could help you with your problem.
> Best wishes,
> Yukun

It works well. Thank you for the help Yukun!
