### ISSUE TITLE
Model Checkpoint source

### ISSUE THREAD

**Issue by alvinchangw** [superrrpotato/Defending-Neural-Backdoors-via-Generative-Distribution-Modeling#2]
Thank you for sharing your code! I was trying to run the defense code defend_cifar_10_all() but it seems that it would need to load a trained model './pytorch-cifar/checkpoint/ckpt.t7'.

May I know how and where you would train this model for the defense?

**Comment by superrrpotato** [comment]
Yes! Thank you for your interest in our project. Please follow this link [pytorch-cifar](https://github.com/kuangliu/pytorch-cifar) to train a cifar10 model under "./pytorch-cifar/" folder as your 1st step. I remember I used the ResNet18 model :) Hope this message is helpful.

**Comment by alvinchangw** [comment]
Ok, thank you for the help!
