### ISSUE TITLE
Does trigger's location may influence the detection result?

### ISSUE THREAD

**Issue by BeStrongok** [superrrpotato/Defending-Neural-Backdoors-via-Generative-Distribution-Modeling#4]
Hello, when i reproduce your project, i find that the location of the trigger you put on the cifar10 dataset is random. But when i use your code to detect my own model which i trained it with the fixed trigger location, your code seems does't work, have you considered this situation?

**Comment by superrrpotato** [comment]
Check line 164 of the main.py file. Have you tried to modify the apply_() function to fix the location of triggers?

**Comment by BeStrongok** [comment]
Yes, when i modify the apply_() function to fix the location of triggers, the detection result is correct. But in the actual situation, the location of the trigger is not known before the detection.

**Comment by BeStrongok** [comment]
So i think when detect the fixed loaction backdoor model, i must specify the location of trigger in apply_() function to get the correct result, may be this is a small limitation in pratical situation. Hope to get your guidance, thank you very much！！

**Comment by superrrpotato** [comment]
Yess...I understand your scenario. When that is the case (I countered it before, during the CSAW 19 competition held by NYU). I choose to scan the location line by line (for i in line_index: for j in column index: detect backdoor with a fixed size), and run the detection algorithm for each location. The computational overhead is quite large, but for once-time detection, it would still be acceptable. Hope that helps :)

**Comment by BeStrongok** [comment]
Thank you for your advice, your code is very helpful! :)
